# fly.toml app configuration file generated for petstore-search-service on 2024-11-06T18:13:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'petstore-search-service'
primary_region = 'bom'

[build]

[env]
  'db.connection.password' = 'MoistMiser!@3'
  'db.connection.url' = 'jdbc:mysql://monolith-mysql.internal:3306/petstore_schema?useSSL=false'
  'db.connection.username' = 'ajay'
  'typesense.apiKey' = 'JznsrBqgz7WClkaPnPVuz66eiyULOBDQ'
  'typesense.host' = '2fayuv1q8ezrgm9np-1.a1.typesense.net'
  'typesense.port' = '443'
  'typesense.protocol' = 'https'

[http_service]
  internal_port = 8085
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
