server:
  port: 8085
  host: 0.0.0.0

app:
    greeting: "Hello"

typesense:
  protocol: "http"
  host: "localhost"
  port: 8108
  apiKey: "ltMhCKNH3kTD0g0HzkXpPq96iBSFxVVIjQAHtK6lH0URkPTv"

db:
  source: "jdbc"
  connection:
    url: "jdbc:mysql://127.0.0.1:3306/petstore_schema?useSSL=false"
    username: "root"
    password: "MoistMiser!@3"
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: "SELECT 0"

    #Product Queries
    fetch-products: "SELECT * FROM Product WHERE indexed = 0"
    fetch-deleted-products: "SELECT * FROM DeletedProducts WHERE deleted = 0"